apiVersion: v1
kind: Service
metadata:
  name: backend-metrics-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend-dev
  ports:
    - name: metrics-port
      protocol: TCP
      port: 9090
      targetPort: 9090