apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: openvidu-recordings
  name: openvidu-recordings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
