apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.openvidu.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: openvidu-server
  name: openvidu-server
spec:
  ports:
    - name: "25565"
      port: 25565
      targetPort: 4443
    - name: "50000"
      port: 50000
      protocol: UDP
      targetPort: 50000
    - name: "50001"
      port: 50001
      protocol: UDP
      targetPort: 50001
    - name: "50002"
      port: 50002
      protocol: UDP
      targetPort: 50002
    - name: "50003"
      port: 50003
      protocol: UDP
      targetPort: 50003
    - name: "50004"
      port: 50004
      protocol: UDP
      targetPort: 50004
    - name: "50005"
      port: 50005
      protocol: UDP
      targetPort: 50005
    - name: "50006"
      port: 50006
      protocol: UDP
      targetPort: 50006
    - name: "50007"
      port: 50007
      protocol: UDP
      targetPort: 50007
    - name: "50008"
      port: 50008
      protocol: UDP
      targetPort: 50008
    - name: "50009"
      port: 50009
      protocol: UDP
      targetPort: 50009
    - name: "50010"
      port: 50010
      protocol: UDP
      targetPort: 50010
    - name: "50011"
      port: 50011
      protocol: UDP
      targetPort: 50011
    - name: "50012"
      port: 50012
      protocol: UDP
      targetPort: 50012
    - name: "50013"
      port: 50013
      protocol: UDP
      targetPort: 50013
    - name: "50014"
      port: 50014
      protocol: UDP
      targetPort: 50014
    - name: "50015"
      port: 50015
      protocol: UDP
      targetPort: 50015
    - name: "50016"
      port: 50016
      protocol: UDP
      targetPort: 50016
    - name: "50017"
      port: 50017
      protocol: UDP
      targetPort: 50017
    - name: "50018"
      port: 50018
      protocol: UDP
      targetPort: 50018
    - name: "50019"
      port: 50019
      protocol: UDP
      targetPort: 50019
    - name: "50020"
      port: 50020
      protocol: UDP
      targetPort: 50020
  selector:
    io.kompose.service: openvidu-server
