apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.openvidu.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: openvidu-server
  name: openvidu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openvidu-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.openvidu.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: openvidu-server
    spec:
      containers:
        - env:
            - name: CERTIFICATE_TYPE
              value: selfsigned
            - name: KMS_MAX_PORT
              value: "50020"
            - name: KMS_MIN_PORT
              value: "50000"
            - name: OPENVIDU_CDR
              value: "false"
            - name: OPENVIDU_DOMAIN_OR_PUBLIC_IP
              value: localhost
            - name: OPENVIDU_PORT
              value: "4443"
            - name: OPENVIDU_RECORDING
              value: "true"
            - name: OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT
              value: "120"
            - name: OPENVIDU_RECORDING_NOTIFICATION
              value: publisher_moderator
            - name: OPENVIDU_RECORDING_PATH
              value: /opt/openvidu/recordings
            - name: OPENVIDU_RECORDING_PUBLIC_ACCESS
              value: "true"
            - name: OPENVIDU_SECRET
              value: MY_SECRET
            - name: OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH
              value: "1000"
            - name: OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH
              value: "1000"
            - name: OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH
              value: "300"
            - name: OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH
              value: "300"
            - name: OPENVIDU_WEBHOOK
              value: "false"
            - name: OV_CE_DEBUG_LEVEL
              value: INFO
          image: openvidu/openvidu-dev:2.30.0
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:25565/openvidu/api/config
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: openvidu-server-dev
          ports:
            - containerPort: 4443
              protocol: TCP
            - containerPort: 50000
              protocol: UDP
            - containerPort: 50001
              protocol: UDP
            - containerPort: 50002
              protocol: UDP
            - containerPort: 50003
              protocol: UDP
            - containerPort: 50004
              protocol: UDP
            - containerPort: 50005
              protocol: UDP
            - containerPort: 50006
              protocol: UDP
            - containerPort: 50007
              protocol: UDP
            - containerPort: 50008
              protocol: UDP
            - containerPort: 50009
              protocol: UDP
            - containerPort: 50010
              protocol: UDP
            - containerPort: 50011
              protocol: UDP
            - containerPort: 50012
              protocol: UDP
            - containerPort: 50013
              protocol: UDP
            - containerPort: 50014
              protocol: UDP
            - containerPort: 50015
              protocol: UDP
            - containerPort: 50016
              protocol: UDP
            - containerPort: 50017
              protocol: UDP
            - containerPort: 50018
              protocol: UDP
            - containerPort: 50019
              protocol: UDP
            - containerPort: 50020
              protocol: UDP
          volumeMounts:
            - mountPath: /opt/openvidu
              name: openvidu-data
            - mountPath: /opt/openvidu/recordings
              name: openvidu-recordings
      restartPolicy: Always
      volumes:
        - name: openvidu-data
          persistentVolumeClaim:
            claimName: openvidu-data
        - name: openvidu-recordings
          persistentVolumeClaim:
            claimName: openvidu-recordings
