apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-dev-podmonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: backend-dev
  podMetricsEndpoints:
  - port: '9090'
    path: '/actuator/prometheus'