apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      serviceAccountName: crema-app-ksa
      nodeSelector:
        disktype: application
      containers:
      - name: backend
        image: asia-northeast3-docker.pkg.dev/coffee-and-commit/coffee/crema-backend:43922fb
        ports:
        - containerPort: 8080
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: crema-app-config
        - secretRef:
            name: crema-app-secret

      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--private-ip"
          - "coffee-and-commit:asia-northeast3:goorm"
          - "--workload-identity"